-- Tạo các bảng cho database
CREATE TABLE KHACHHANG
(
	MAKH  VARCHAR(5) PRIMARY KEY,
	HOTEN NVARCHAR(40),
	TUOI INT,
	CCCD_CMND VARCHAR(12),
	SDT VARCHAR(12),
	GIOITINH NVARCHAR(3),
	SOLUONG INT
)

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(4) PRIMARY KEY,	
	TENTK VARCHAR(40),
	MATKHAU VARCHAR(96),
	HOTEN NVARCHAR(40),
	TUOI INT,
	NGVL SMALLDATETIME,
	SDT VARCHAR(12),
	CCCD_CMND VARCHAR(12),
	GIOITINH NVARCHAR(3)
)

CREATE TABLE PHONG
(
	MAPHONG INT IDENTITY(1,1) PRIMARY KEY,
	TENPHONG NVARCHAR(20),
	TRANGTHAI NVARCHAR(20),
	MALP VARCHAR(4)
)


CREATE TABLE LOAIPHONG
(
	MALP VARCHAR(4) PRIMARY KEY,
	TENLP NVARCHAR(20),
	GIA MONEY
)

CREATE TABLE DICHVU
(
	MADV VARCHAR(3) PRIMARY KEY,
	TENDV NVARCHAR(40),
	GIA MONEY
)

CREATE TABLE HOADON
(
	MADV VARCHAR(3),
	MAHD INT IDENTITY(1000,1) PRIMARY KEY,
	NGAYLAP SMALLDATETIME,
	HINHTHUCTT NVARCHAR(20),
	TINHTIEN MONEY,
	MAKH VARCHAR(5),
	MANV VARCHAR(4),
	CheckIn SMALLDATETIME,
	CheckOut SMALLDATETIME,
	SOPHONG INT,
	KHUYENMAI TINYINT
)

CREATE TABLE HOADONDA
(
	MAHDDA INT IDENTITY(10000,1) PRIMARY KEY,
	NGAYLAP SMALLDATETIME,
	TONGTIEN MONEY,
	MAKH VARCHAR(5),
	MANV VARCHAR(4),
	SOLUONG INT,
	TENPHONG NVARCHAR(20)
)

CREATE TABLE DATDV
(
	MADV VARCHAR(3),
	MAKH VARCHAR(5),
	CONSTRAINT FK_DATDV PRIMARY KEY(MADV,MAKH),
	TONGTIEN MONEY
)

CREATE TABLE DATPHONG
(
	MAKH VARCHAR(5),
	MAPHONG INT,
	TENPHONG NVARCHAR(20),
	MAHD INT,
	NGAYDAT SMALLDATETIME,
	NGAYDI SMALLDATETIME,
	THANHTOAN NVARCHAR(10),
	MANV VARCHAR(4)
)

CREATE TABLE DOANHTHU
(
	DOANHTHU MONEY,
	THOIGIAN SMALLDATETIME
)

CREATE TABLE THUCPHAM
(
	MATP INT IDENTITY(1000,1) PRIMARY KEY,
	TENTP NVARCHAR(40),
	GIATIEN MONEY,
	MALTP CHAR(3)
)

CREATE TABLE DATTP
(
	MAHDDA INT,
	MAKH VARCHAR(5),
	MATP INT,
	MALTP CHAR(3),
	TENTP NVARCHAR(40),
	SOLUONG INT,
	TONGTIEN MONEY
)


-- Thêm ràng buộc khóa ngoại ở các bảng
ALTER TABLE PHONG ADD CONSTRAINT FK_MALP FOREIGN KEY (MALP) REFERENCES LOAIPHONG(MALP)
ALTER TABLE DATPHONG ADD CONSTRAINT DP_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH)
ALTER TABLE DATPHONG ADD CONSTRAINT DP_MAPHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG) 
 
ALTER TABLE HOADON ADD CONSTRAINT HD_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH) 
ALTER TABLE HOADON ADD CONSTRAINT HD_MADV FOREIGN KEY (MADV) REFERENCES DICHVU(MADV)
ALTER TABLE HOADON ADD CONSTRAINT HD_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE HOADONDA ADD CONSTRAINT HDDA_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH) 
ALTER TABLE HOADONDA ADD CONSTRAINT HDDA_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE DATPHONG ADD CONSTRAINT FK_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE DATDV ADD CONSTRAINT DDV_MADV FOREIGN KEY (MADV) REFERENCES DICHVU(MADV)
ALTER TABLE DATDV ADD CONSTRAINT DDV_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH) 
ALTER TABLE DATTP ADD CONSTRAINT DTP_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH) 
ALTER TABLE DATTP ADD CONSTRAINT DTP_MATP FOREIGN KEY (MATP) REFERENCES THUCPHAM (MATP) 


-- Thêm các ràng buộc toàn vẹn
ALTER TABLE PHONG ADD CONSTRAINT CHK_TRANGTHAI CHECK (TRANGTHAI IN(N'TRỐNG',N'ĐÃ THUÊ'))
ALTER TABLE THUCPHAM ADD CONSTRAINT CHK_MALTP CHECK (MALTP IN(N'FOD',N'DRK'))
ALTER TABLE DATPHONG ADD CONSTRAINT CHK_NGAYDI CHECK (NGAYDI > NGAYDAT)


-- Thêm tài khoản mặc định cho chủ doanh nghiệp
INSERT INTO NHANVIEN(MANV, TENTK,MATKHAU) VALUES ('ADM', 'ADMIN','8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92')


SET DATEFORMAT DMY 


-- Tạo các view để in hóa đơn
CREATE VIEW Invoice AS
SELECT A.MAHD, MAPHONG, TENPHONG, NGAYLAP, NGAYDAT, NGAYDI, TINHTIEN
FROM HOADON A
INNER JOIN DATPHONG B ON A.MAHD = B.MAHD

CREATE VIEW Information AS
SELECT MAHD, HOTEN, CCCD_CMND, SDT, NGAYLAP, CheckIn, CheckOut, FORMAT(TINHTIEN, '###,###,###') AS TONGTIEN
FROM HOADON A
INNER JOIN KHACHHANG B ON A.MAKH = B.MAKH

CREATE VIEW Food AS
SELECT MAHDDA, A.MATP, A.TENTP, B.MALTP, SOLUONG, FORMAT(TONGTIEN, '###,###,###') AS TONGTIEN 
FROM DATTP A
INNER JOIN THUCPHAM B ON A.MATP = B.MATP

CREATE VIEW InformationFood AS
SELECT MAHDDA, NGAYLAP, FORMAT(TONGTIEN, '###,###,###') AS TONGTIEN, TENPHONG 
FROM HOADONDA